// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3e5O1qskSGsLL07G_l0OzXxfWC-fYZ8g',
    appId: '1:263928593067:web:1d59315446401098da95ee',
    messagingSenderId: '263928593067',
    projectId: 'ecommerce-flutter-ca1d0',
    authDomain: 'ecommerce-flutter-ca1d0.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-ca1d0.appspot.com',
    measurementId: 'G-347N8DFHQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPdRfJo-RSL1V1A2JY2_4eC8BJoZU5LcI',
    appId: '1:263928593067:android:a8d8402b97586cabda95ee',
    messagingSenderId: '263928593067',
    projectId: 'ecommerce-flutter-ca1d0',
    storageBucket: 'ecommerce-flutter-ca1d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBQ7wchqxjDn7n_t-0aaAmF22IdvXT54k',
    appId: '1:263928593067:ios:8adb82a35134e7afda95ee',
    messagingSenderId: '263928593067',
    projectId: 'ecommerce-flutter-ca1d0',
    storageBucket: 'ecommerce-flutter-ca1d0.appspot.com',
    iosBundleId: 'com.example.ecommerceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBQ7wchqxjDn7n_t-0aaAmF22IdvXT54k',
    appId: '1:263928593067:ios:8adb82a35134e7afda95ee',
    messagingSenderId: '263928593067',
    projectId: 'ecommerce-flutter-ca1d0',
    storageBucket: 'ecommerce-flutter-ca1d0.appspot.com',
    iosBundleId: 'com.example.ecommerceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3e5O1qskSGsLL07G_l0OzXxfWC-fYZ8g',
    appId: '1:263928593067:web:003d272b86fddf68da95ee',
    messagingSenderId: '263928593067',
    projectId: 'ecommerce-flutter-ca1d0',
    authDomain: 'ecommerce-flutter-ca1d0.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-ca1d0.appspot.com',
    measurementId: 'G-TTM6XWQ98F',
  );
}
